#define RESULTS_FILE "results.csv"
#define EVALUATIONS_BUDGET 1000
#define MIN_MUTATIONS 1
#define MAX_MUTATIONS 400
#define DB_PATH "results.sqlite"
#define OPTIMIZABLE_SECTION_FLAG "OPTIMIZABLE_SECTION"